spec_version: 3.0
package: arbitrage_vault

database:
  kind: postgres
  host: ${POSTGRES_HOST:-localhost}
  port: ${POSTGRES_PORT:-5432}
  user: ${POSTGRES_USER:-huydo}
  password: ${POSTGRES_PASSWORD:-huydo2105}
  database: ${POSTGRES_DB:-huydo}

hasura:
  url: http://hasura:8080
  admin_secret: ${ADMIN_SECRET:-huydo2105}
  select_limit: ${SELECT_LIMIT:-1000}
  camel_case: true
  allow_aggregations: true
  rest: true

contracts:
  vault:
    address: 0x895Ea1c1A1EF1EceF0Fb822e33BE0bB9d493559d
    typename: ArbitrageVault

datasources:
  subsquid:
    kind: evm.subsquid
    url: ${SUBSQUID_URL:-https://v2.archive.subsquid.io/network/etherlink-mainnet}
  etherscan:
    kind: evm.etherscan
    url: ${ETHERSCAN_URL:-https://api.etherscan.io/v2/api?chainId=42793}
    api_key: ${ETHERSCAN_API_KEY:-changeme}
  evm_node:
    kind: evm.node
    url: ${RPC_URL:-https://node.mainnet.etherlink.com}
    http:
      batch_size: 50
      ratelimit_rate: 1      
      ratelimit_period: 2 # Wait 2 seconds between requests
      retry_count: 30
      retry_sleep: 5
      connection_timeout: 120

indexes:
  vault_events:
    kind: evm.events
    datasources:
      - etherscan
      - evm_node
      - subsquid
    handlers:
      - callback: on_multi_hop_arbitrage_executed
        contract: vault
        name: MultiHopArbitrageExecuted
      - callback: on_dex_whitelisted
        contract: vault
        name: DexWhitelisted
      - callback: on_deposit
        contract: vault
        name: Deposit
      - callback: on_withdraw
        contract: vault
        name: Withdraw
    first_level: 41517933

hooks:
  run_arbitrage:
    callback: run_arbitrage
    atomic: false
    args:
      vault_address: str
      min_profit_usd: float

jobs:
  arbitrage_cycle:
    hook: run_arbitrage
    crontab: "* * * * *" # Every 3 minutes
    args:
      vault_address: "0x895Ea1c1A1EF1EceF0Fb822e33BE0bB9d493559d"
      min_profit_usd: 0