services:
  indexer:
    build: .
    depends_on:
      db:
        condition: service_healthy
    entrypoint: /bin/sh
    command: -c "dipdup -c dipdup.yml init && dipdup -c dipdup.yml run"
    restart: "no"
    networks:
      - default
    volumes:
      - .:/home/dipdup
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-huydo2105}
      - POSTGRES_USER=${POSTGRES_USER:-huydo}
      - POSTGRES_DB=${POSTGRES_DB:-huydo}
      - ADMIN_SECRET=${ADMIN_SECRET:-huydo2105}
      - ETHERSCAN_URL=${ETHERSCAN_URL:-https://api.etherscan.io/v2/api?chainId=}
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY:-}
      - RPC_URL=${RPC_URL:-https://node.mainnet.etherlink.com}
      - SUBSQUID_URL=${SUBSQUID_URL:-https://v2.archive.subsquid.io/network/etherlink-mainnet}
      - ORACLE_ADDRESS=${ORACLE_ADDRESS:-}
      - WAGER_ADDRESS=${WAGER_ADDRESS:-}
      - POOL_ADDRESS=${POOL_ADDRESS:-}
      - GEMINI_API_KEY=${GOOGLE_API_KEY:-}
      - STRATEGIST_PRIVATE_KEY=${STRATEGIST_PRIVATE_KEY:-}

  db:
    image: postgres:15
    restart: always
    networks:
      - default
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-huydo}
      - POSTGRES_DB=${POSTGRES_DB:-huydo}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-huydo2105}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U huydo -d huydo"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - 5433:5432

  hasura:
    image: hasura/graphql-engine:v2.35.0
    ports:
      - 8181:8080
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - default
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgres://${POSTGRES_USER:-huydo}:${POSTGRES_PASSWORD:-huydo2105}@db:5432/${POSTGRES_DB:-huydo}
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_DEV_MODE=true
      - HASURA_GRAPHQL_ENABLED_LOG_TYPES=startup, http-log, webhook-log, websocket-log, query-log
      - HASURA_GRAPHQL_ADMIN_SECRET=${ADMIN_SECRET:-huydo2105}
      - HASURA_GRAPHQL_UNAUTHORIZED_ROLE=user
      - HASURA_GRAPHQL_STRINGIFY_NUMERIC_TYPES=true

volumes:
  db: