# generated by DipDup 8.5.1

from __future__ import annotations

from pydantic import BaseModel


class ArbitrageExecutedPayload(BaseModel):
    strategist: str
    dexBuy: str
    dexSell: str
    tokenTrade: str
    profit: int
