# generated by DipDup 8.5.1

from __future__ import annotations

from pydantic import BaseModel


class MultiHopArbitrageExecutedPayload(BaseModel):
    strategist: str
    route: list[str]
    pools: list[str]
    hops: int
    profit: int
