# generated by DipDup 8.5.1

from __future__ import annotations

from pydantic import BaseModel


class WithdrawPayload(BaseModel):
    sender: str
    receiver: str
    owner: str
    assets: int
    shares: int
